#! version
version: '3.0'
#! version

#! spacetime
spacetime:
  system: BCRS
#! spacetime

#! mappings
mappings:
  # Map spice ephemeris constant to constant book
  - name: spiceConstMap
    data:
      BODY399_GM: EarthGM
#! mappings

#! ephemeris
ephemeris:
  # Named ephemeris objects with files to load
  - name: de405
    files:
      - share/test/unxp2000.405
    cache: false # Do not load file to memory
  # Another ephemeris for constants, default is loading file contents to memory
  - name: gm431
    files:
      - share/test/gm_de431.tpc
#! ephemeris

#! stations
stations:
  # Create station database for Earth ground stations
  - name: earthStations
    file: share/test/GroundStationsDatabase.json
#! stations

#! constants
constants:
  # Load constants from ephemeris, with optional additional mapping between names
  ephemeris:
    - source: gm431
      mapping: spiceConstMap
  # Add user defined data: always specified in SI (km, kg, s)
  data:
    EarthGM: 398600.4415 # Override default Earth GM
    MoonGM: 4902.8029535968 # Override default Moon GM
#! constants

#! parameters
parameters:
  - name: mass
    type: Parameter
    value: 2160 kg
  - name: Euclid_cd
    type: Parameter
    value: '1.7'
  - name: Euclid_cr
    type: Parameter
    value: '1.5'
#! parameters

#! frames
frames:
  - name: ephem1
    type: Ephem
    config:
      source: de405
    #  mapping: interplanetary   # Custom (additional) mapping supplied
    # We can also add ipf files, with optional mapping
  - name: ITRF
    type: AxesOrient
    config:
      model: IERS2000   # Earth body fixed model
      nutation: share/test/nutation2000A.ipf   # Supply nutation interpolation file
      erp: ''   # Use no pole correction
  - name: Mars
    type: AxesOrient
    config:
      model: MarsIAU2009   # Mars body fixed model
    # Specify rotating axes based on two points
  - name: EarthMoonRot
    type: AxesLocalOrbital
    config:
      center: Earth   # Center of rotating frame
      target: Moon   # Target point of direction X (or Y)
      axes: Pos   # Position (X) or velocity (Y) based
    # Add topocentric axes from station database
  - name: stations1
    type: Stations
    config:
      source: earthStations
      points: false
  - name: stations2
    type: Stations
    config:
      source: earthStations
      axes: false
  - name: PlaneOfSky
    type: AxesLocalOrbital
    config:
      center: New_Norcia
      target: Euclid_center
      axes: RAC
  - name: EuclidLOF
    type: AxesLocalOrbital
    config:
      center: Earth
      target: Euclid_center
      axes: RAC
#! frames

#! bodies
bodies:
  # Earth as body with Earth as the center of the body from the frames plugin
  - name: Earth
    point: Earth
    # Add non-spherical gravity field from file, attached to body-fixed axes ITRF
    gravity:
      - EarthGrav
    gm: EarthGrav
  - name: Sun
    point: Sun
  # Define Moon as point mass
  - name: Moon
    point: Moon
#! bodies

#! gravity
gravity:
  # Earth, Moon and Sun system gravity
  - name: EMS
    bodies:
      - Sun # Sun top tree level
      - Earth # Earth top tree level, COI switch possible to root (SSB)
      # Define Moon to be below Earth, so COI switch possible between Earth and Moon
      - center: Moon
        parent: Earth
        barycenter: ''
#! gravity

#! atmosphere
atmosphere:
  - name: EarthAtmos
    type: nrlmsise00 # Specific model for Earth
    config:
      point: Earth
      axes: ITRF # Atmosphere glued to Earth body-fixed frame
      file: share/test/solmag.ipf # Use solar activity file
#! atmosphere

#! dynamics
dynamics:
  - name: Simple
    type: SystemGravity
    config:
      model: EMS

  - name: EMS_gravity
    type: SystemGravity
    config:
      model: EMS

  - name: srp
    type: SimpleSRP
    config:
      mass: Euclid_mass
      area: Euclid_srp_area
      cr: Euclid_srp_cr
      occulters:
        - Earth

  - name: drag
    type: SimpleDrag
    config:
      atmosphere: EarthAtmos
      mass: Euclid_mass
      area: Euclid_drag_area
      cd: Euclid_drag_cd

  - name: EMS
    type: Combined
    config:
      - EMS_gravity
      - srp
      - drag
#! dynamics

#! spacecraft
spacecraft:
 # Configuration for Euclid spacecraft
  - name: Euclid
    mass: mass
    # Solar radiation modelling surface properties
    srp:
      area: 12 m^2
      cr: Euclid_cr # Reflectivity coefficient
    # Drag modelling surface properties
    drag:
      area: 8 m^2
      cd: Euclid_cd # Ballistic coefficient
    thrusters:
      # Define a "main" thruster block with thrust magnitude and Isp
      - name: main
        thrust: 100 N
        isp: 320 s
#! spacecraft

#! lightTime
lightTime:
  - name: solarSystem
    bodies:
      - Sun
      - Earth
      - Moon
    refCenter: SSB
    refAxes: ICRF
#! lightTime
sphericalHarmonics:
  - name: EarthGrav
    type: File
    config:
      point: Earth
      degree: 16
      order: 16
      axes: ITRF
      file: share/test/eigen05c_80_sha.tab